CREATE OR REPLACE TABLE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS" AS 
SELECT table_name,
       column_name,
       data_type,
       'N' AS R1A1,
       'N' AS R1A2,
       'N' AS R1A3,
       'N' AS R2A1,
       'N' AS R3A1,
       'N' AS R4A1,
       'N' AS R5A2,
       'N' AS R6A2,
       'N' AS R12A1
     FROM "SHARED_TOOLS_DEV"."INFORMATION_SCHEMA"."COLUMNS" 
     WHERE table_name IN ('ETLF_EXTRACT_CONFIG');

//---------------------------------------------UPDATE------------------------------------------------------------

UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R1A1 = 'Y', 
    R1A2 = 'Y', 
    R1A3 = 'Y', 
    R2A1 = 'Y', 
    R4A1 = 'Y', 
    R5A2 = 'Y', 
    R6A2 = 'Y',
    R12A1 = 'Y' 
WHERE COLUMN_NAME IN ('SOURCE_TABLE', 'GROUP_ID', 'EXTRACT_SCHEMA', 'SOURCE_SYSTEM_ID', 'TARGET_SYSTEM_ID', 'TARGET_TABLE', 'ACTIVE', 'DIEONMISMATCH', 'NOTIFICATIONEMAILS'); 

-- no need to show on form
UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R1A1 = 'D', 
    R1A2 = 'D', 
    R1A3 = 'D', 
    R2A1 = 'D', 
    R4A1 = 'D', 
    R5A2 = 'D', 
    R6A2 = 'D',
    R12A1 = 'D'
WHERE COLUMN_NAME IN ('EXTRACT_CONFIG_ID', 'ROUTE_ID', 'ACTION_ID', 'CREATEDDT', 'LASTMODIFIEDDT');

UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R1A1 = 'O', 
    R1A2 = 'O', 
    R1A3 = 'O', 
    R2A1 = 'O', 
    R4A1 = 'O', 
    R5A2 = 'O', 
    R6A2 = 'O',
    R12A1 = 'O'
WHERE COLUMN_NAME IN ('FLEX1', 'FLEX2', 'FLEX3'); 

UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R1A1 = 'O', 
    R1A2 = 'O', 
    R1A3 = 'O'
WHERE COLUMN_NAME IN ('CURSOR_SIZE', 'REF_CONFIG_ID');

--'TGT_TABLE_ACTION'
UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R1A1 = 'Y', 
    R1A2 = 'Y', 
    R1A3 = 'Y', 
    R4A1 = 'Y', 
    R6A2 = 'Y'
WHERE COLUMN_NAME IN ('TGT_TABLE_ACTION'); 

--R1A3
UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R1A3 = 'Y' 
WHERE COLUMN_NAME IN ('PX_BOUNDARYSCHEMA', 'PX_SPLITNUM', 'PX_BOUNDARYTBL', 'PX_PARALLELEXECNUM' ); 

--R4A1
UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R4A1 = 'Y' 
WHERE COLUMN_NAME IN ('SRCFILEHEADER', 'SRCFILEDELIMETER', 'SRCFILEPATHNAME', 'SOURCE_FILE_TYPE' );

UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R4A1 = 'O' 
WHERE COLUMN_NAME IN ('SRS_FILE_XLSX_SHEET_NAME');

UPDATE "SHARED_TOOLS_DEV"."ETL"."ETLF_EXTRACT_CONFIG_REQUIREMENTS"
SET R4A1 = 'N' 
WHERE COLUMN_NAME IN ('SOURCE_SYSTEM_ID');