export function mergeUpdateCatalogEntitiesFromView(){
    const sql =  ` MERGE INTO SHARED_TOOLS_DEV.ETL.CATALOG_ENTITIES TT
    USING (
        SELECT 
          TARGET_DATABASE,
          TARGET_SCHEMA,
          TARGET_TABLE,
          CAST( NULL AS STRING) COMMENTS,
          CAST(ABS(HASH(UPPER(TRIM(TARGET_DATABASE)),UPPER(TRIM(TARGET_SCHEMA)),UPPER(TRIM(TARGET_TABLE)))) AS STRING) CATALOG_ENTITIES_ID
        FROM "GR_DEV"."DIH"."DATA_CATALOG_VW"
        GROUP BY 
          TARGET_TABLE,
          TARGET_SCHEMA,
          TARGET_DATABASE
    ) st 
    ON (TT.CATALOG_ENTITIES_ID = ST.CATALOG_ENTITIES_ID)
    WHEN NOT matched THEN
      INSERT (
          TARGET_DATABASE,
          TARGET_SCHEMA,
          TARGET_TABLE,
          COMMENTS,
          CATALOG_ENTITIES_ID
      ) 
      VALUES 
      (
          ST.TARGET_DATABASE,
          ST.TARGET_SCHEMA,
          ST.TARGET_TABLE,
          ST.COMMENTS,
          ST.CATALOG_ENTITIES_ID
      );`;

    return sql
}

export function mergeUpdateCatalogItemsFromView(){
    const sql =  `MERGE INTO SHARED_TOOLS_DEV.ETL.CATALOG_ITEMS TT
    USING (
      SELECT 
        COLUMN_NAME, DATA_TYPE, PII, DENSITY, SEARCH_KEY,
        CAST( NULL AS STRING) COMMENTS,
        CAST(ABS(HASH(UPPER(TRIM(TARGET_DATABASE)),UPPER(TRIM(TARGET_SCHEMA)),UPPER(TRIM(TARGET_TABLE)),UPPER(TRIM(COLUMN_NAME)))) AS STRING) CATALOG_ITEMS_ID
        CAST(ABS(HASH(UPPER(TRIM(TARGET_DATABASE)),UPPER(TRIM(TARGET_SCHEMA)),UPPER(TRIM(TARGET_TABLE)))) AS STRING) CATALOG_ENTITIES_ID
      FROM "GR_DEV"."DIH"."DATA_CATALOG_VW"
      GROUP BY
        COLUMN_NAME
        TARGET_TABLE,
        TARGET_SCHEMA,
        TARGET_DATABASE
    ) st 
    ON (TT.CATALOG_ITEMS_ID = ST.CATALOG_ITEMS_ID)
    WHEN NOT matched THEN
    INSERT (
        COLUMN_NAME, DATA_TYPE, PII, DENSITY, SEARCH_KEY, COMMENTS, CATALOG_ITEMS_ID, CATALOG_ENTITIES_ID 
    ) 
    VALUES 
    (
        ST.COLUMN_NAME, ST.DATA_TYPE, ST.PII, ST.DENSITY, ST.SEARCH_KEY, ST.COMMENTS, ST.CATALOG_ITEMS_ID, ST.CATALOG_ENTITIES_ID
    );`;
    return sql;
}

export function mergeUpdateEntityLineageFromView(){
    const sql =  ``;
    return sql;
}